version: '3.7'
services:
  test:
    build:
      context: ./
      args:
        NODE_ENV: development
    image: placa:test
    command: ["npm", "test"]
    environment:
      - NODE_ENV=test
    volumes:
      - ./test:/home/node/app/test
      - ./lib:/home/node/app/lib
      - ./index.js:/home/node/app/index.js
